# to fix
version: "3.7"

services:
  reverse:
    hostname: nginx-reverse-proxy
    image: nginx:stable-alpine
    container_name: nginx-alpine
    volumes:
      - $PWD/nginx-conf/myapp/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx-conf/myapp/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - 80:80
      - 433:433

volumes:
  nginx-conf:
networks:
  myapp-net:
    driver: bridge
